name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.2.20176.6
    - name: Install dependencies
      working-directory: './JDI.Light'
      run: dotnet restore
    - name: Build
      working-directory: './JDI.Light'
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: './JDI.Light'
      run: dotnet test --no-restore --verbosity normal
